### ISSUE TITLE
sm_boost does not build with boost 1.58 (os x)

### ISSUE THREAD

**Issue by burrimi** [ethz-asl/Schweizer-Messer#142]
catkin_ws/src/schweizer_messer/sm_boost/include/boost/portable_binary_iarchive.hpp:30:10: fatal error: 'boost/archive/shared_ptr_helper.hpp' file not found
#include <boost/archive/shared_ptr_helper.hpp>

seems like boost 1.58 moved the file to
http://www.boost.org/doc/libs/1_58_0/boost/serialization/shared_ptr_helper.hpp
and changed the interface.

A simple hack is to remove the shared_ptr_helper completely to get it compiling, but this is probably a bad idea..

**Comment by HannesSommer** [comment]
Thanks. Does PR #143 work for you, @burrimi  ?

**Comment by HannesSommer** [comment]
This seems to be solved with #143 .
